SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `ventas`.`entrada_historico` CHANGE COLUMN `id_entrada_historico` `id_entrada_historico` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT  
, ADD PRIMARY KEY (`id_entrada_historico`) ;

ALTER TABLE `ventas`.`historico` CHANGE COLUMN `id_historico` `id_historico` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT  
, ADD PRIMARY KEY (`id_historico`) ;

ALTER TABLE `ventas`.`paciente` DROP COLUMN `historico_id_historico` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
